/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * module registration is done by the runtime, no need to explicitly do it now.
 * run $napi build
 */
export declare function getKeys(): Array<Buffer>
export declare function encrypt(plain: number, clientKeySer: Buffer): Buffer
export declare function encryptPublicKey(plain: number, publicKeySer: Buffer): Buffer
export declare function greaterThan(cipherASer: Buffer, cipherBSer: Buffer, serverKeySer: Buffer): Buffer
export declare function decrypt(cipherSer: Buffer, clientKeySer: Buffer): boolean
