/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * module registration is done by the runtime, no need to explicitly do it now.
 * run $napi build
 */
export declare function getKeys(): Array<Array<number>>
export declare function encrypt(plain: number, clientKeySer: Array<number>): Array<number>
export declare function encryptPublicKey(plain: number, compressedPublicKeySer: Array<number>): Array<number>
export declare function greaterThan(cipherASer: Array<number>, cipherBSer: Array<number>, compressedServerKeySer: Array<number>): Array<number>
export declare function decrypt(cipherSer: Array<number>, clientKeySer: Array<number>): boolean
